package aima.core.environment.CannibalsAndMissionaries;

/**
 * Created by benoit on 14/09/2018.
 */
public enum CannibalsAndMissionariesAction {
    PUT_ONE_CANNIBAL_FROM_BOAT_TO_RIGHT_RIVER,
    PUT_ONE_CANNIBAL_FROM_BOAT_TO_LEFT_RIVER,
    PUT_ONE_CANNIBAL_FROM_RIGHT_RIVER_TO_BOAT,
    PUT_ONE_CANNIBAL_FROM_LEFT_RIVER_TO_BOAT,
    PUT_ONE_MISSIONARY_FROM_BOAT_TO_RIGHT_RIVER,
    PUT_ONE_MISSIONARY_FROM_BOAT_TO_LEFT_RIVER,
    PUT_ONE_MISSIONARY_FROM_RIGHT_RIVER_TO_BOAT,
    PUT_ONE_MISSIONARY_FROM_LEFT_RIVER_TO_BOAT,
    MOVE_BOAT
}
